# Generated by Django 6.0.5 on 2026-06-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('data', models.TextField(blank=True)),
                ('com', models.TextField(blank=True)),
                ('titulo', models.CharField(max_length=255)),
                ('photo', models.TextField(blank=True)),
                ('assunto', models.TextField(blank=True)),
                ('user', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
