# Generated by Django 6.0.5 on 2026-06-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('data', models.TextField(blank=True)),
                ('com', models.TextField(blank=True)),
                ('titulo', models.CharField(max_length=255)),
                ('photo', models.TextField(blank=True)),
                ('assunto', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
