# Generated by Django 6.0.5 on 2026-06-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('apellido1', models.CharField(blank=True, max_length=255)),
                ('apellido2', models.CharField(blank=True, max_length=255)),
                ('republica', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(db_column='ID_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
            ],
            options={
                'db_table': 'User_Info',
            },
        ),
    ]
